name: PR Labeler
author: Squareup Limited
description: An action that labels PRs based on their state transitions
inputs:
  pr-number:
    description: The PR number
    required: true
  pr-author:
    description: The author of the PR
    required: true
  repo-token:
    description: The Token for the Github Repo using the action
    required: true
  action-type:
    description: The event that occured on the PR
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
